
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/navbar";
import MaxWidthWrapper from "@/components/maxwidthwrapper";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Navbar />
            <MaxWidthWrapper>
                {children}
            </MaxWidthWrapper>
        </>
    );
}
